#!/bin/sh
#
# auto/config – configuration script for Debian live images
#
# This script initialises the live-build system for the desired
# architecture. It sets the distribution to the current stable Debian
# ("trixie", Debian 13) and enables the archives for
# "contrib", "non-free" and "non-free-firmware" so that drivers and
# proprietary firmware packages are available. The output will be
# a hybrid ISO image that can boot both from optical media and
# USB sticks.
#
# The target architecture can be set via the environment variable ARCH.
# If no architecture is specified, amd64 will be used as default.
# Set ARCH=i386, ARCH=arm64, etc. to build for other architectures.
ARCH=${ARCH:-amd64}

# Invoke live-build with recommended options. These options follow the
# Debian live manual guidelines for creating a custom image【552664018867803†L52-L60】.
lb config \
    --architectures "${ARCH}" \
    --distribution trixie \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer disabled \
    --firmware-binary yes \
    --iso-volume "Debian Recovery ${ARCH}" \
    --linux-flavours generic
